### PR TITLE
Implement transparent pixel support

### LINKED ISSUE #5: Transparency support
It would be very cool if im2a supported transparency.
Partial transparency will be difficult to do, but 100% transparent areas could be mapped to the default terminal background color using `\e[49m`.

It may be necessary to use `▀` and ` ` in addition to `▄` for partial pixels, however.

### PR DESCRIPTION
**Pull request by onitake**
⚠️ **This should not be merged yet. Some edge cases aren't handled correctly.**

Work is done mostly on the pixel code, as that is the trickiest to implement.

Fixes #5 .

### CODE REVIEW

**Comment by tzvetkoff** [comment]
Hey, are you using ImageMagick 6?

**Comment by onitake** [comment]
Yes, 6.9.7 with 16bit color depth support.
This: https://packages.debian.org/sid/imagemagick-6.q16

**Comment by tzvetkoff** [comment]
OK, I'm actually using `7.0.7` locally and `matte()` is renamed to `alpha()` but this is not a problem.

Do you test it with some specific image, or any specific arguments?
I have made the transparency support with a parameter and a threshold, so it will be more flexible.

**Comment by onitake** [comment]
Yes, I have a few test images, but not all them work well.
In particular, bottom pixel transparency seems to be broken sometimes.
I need to debug some more to see what's going on.

A threshold is definitely a good idea, yes. 0xff works well for handcrafted images, but as soon as interpolation comes into play...

**Comment by tzvetkoff** [comment]
OK, I think I've got it.  Thing is, `opacity` is the opposite of `alpha`. :-)
I'll run a few more tests and I'll eventually release `0.6.0` later today.

P.S. If you have any particular images to test with, please share them. :-)

**Comment by tzvetkoff** [comment]
Implemented differently (with support for both ImageMagick 6 & 7) in 103ff7a (`v0.6.0`)

**Pull request closed without merging**
